### ISSUE TITLE
KT files are not extractable

### ISSUE THREAD

**Issue by ilyasOne** [MinBZK/nl-wallet#10]
Fantastic project, truly fascinating!

Just a note, the zip files (Source code zip) on the page, see below cannot be unpacked, KT-files cannot be unpacked.

Web page-https://github.com/MinBZK/nl-wallet/releases/tag/v0.1.25-beta-20240326

**Comment by confiks** [comment]
Hello! May I ask you you mean with "KT-files"? Files with the .kt (Kotlin) extension? Do all files fail to extract or just specific ones? Which operating system and unzip software are you using? The files extract just fine for me, both on Debian and MacOS `unzip`.

The contents of those zip-files are just the repository contents of that tag. If you do a Git clone, and reset to that tag, you'd get the same files as in the zip files.

I hope that helps.

**Comment by ilyasOne** [comment]
Hi!

Apologies for the unclear message.

KT-files are files with extraction .kt.
I use Windows 11 and Unzip zipper. It could also be 7-zip, can't check it now, it was already default installed on my company laptop.

Only the files with .kt extension could not be unpacked.

I clone them already with Git Clone.

Thank you for your time and reaction.







U
