### ISSUE TITLE
Upgrade Instructions to 0.2.2

### ISSUE THREAD

**Issue by hacdias** [MinBZK/nl-wallet#18]
Hi!

I see there's a new version for the verification server. The release notes mention we need to rename `verifier.trust_anchors` to `issuer_trust_anchors`. Unfortunately, that does not seem to be enough. When starting the server, we get the following error:

``` 
Error: missing field `reader_trust_anchors`
```

I can't find any documentation for this field. Additionally, none of this information (renamed field) and the new field are described in the relaying party information: https://github.com/MinBZK/nl-wallet/blob/v0.2.2/documentation/relying-party.md#creating-the-configuration-file

**Comment by peterpaul** [comment]
Thank you for your report, I have updated the release notes and we will update the documentation, which unfortunately will take a bit longer.

**Comment by rubin55** [comment]
Release notes updated with relevant instructions, closing.
