### ISSUE TITLE
[Question] Compatibility with Solid Project?

### ISSUE THREAD

**Issue by Potherca** [MinBZK/nl-wallet#9]
Great project, very interesting. Also very cool to see more open-sourced government projects!

I'm still parsing the architecture and design PDFs, but I was curious how the EUID wallet (specifically the Authn parts) coincides or conflict with the [Solid Project](https://solidproject.org/) (specifically the Identity Provider parts).

The EUID wallet uses SAML, where Solid uses OAuth. But both have a custom extension on top of OIDC... 

Solid uses WebID as identity document (in fact everything in the Storage Pod is Linked Data). I'm not sure (yet) what EUID uses; like I said, I'm still parsing the docs.

I'd be especially interested to learn whether the EUID could actually be used as Identity Provider for Solid Storage Pods.
Things like pseudonyms would also be very interested in that regard.

Anyway, what would be the best way for me to learn more about technical details regarding EUID and/or where can I best ask further questions?

**Comment by confiks** [comment]
As a personal reflection on your question:

I'm not that knowledgeable about the Solid project, and as far as I know, there is no mention of the Solid project in the EUDI ARF.

If I look at Solid Identity Providers, it seems that every such identity provider can choose in which way they'll authenticate users to prove that they own a certain WebID. OIDC is mentioned as an example, but it certainly seems possible to use OpenID4VP at that stage to prove that you own a certain WebID for example by using attributes from your EUDI PID. In the same way, the identity provider could issue a WebID credential to the wallet that can then be verified again for access to a WebID.

**Comment by Potherca** [comment]
For anyone who visits this from a web search, <a href="https://www.igrant.io/"><img alt="igrant.io" width="125" src="https://github.com/user-attachments/assets/177eefa6-a60c-4460-b3e6-ed8e8319a346" /></a> offers EU Digital Identity Wallet (EUDI) fully aligned with eIDAS 2.0 [using Solid][1] as a _backend_.

[1]: https://www.igrant.io/datapod.html
